/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhookRouteImport } from './routes/webhook'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedMusicasRouteImport } from './routes/_authenticated.musicas'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated.downloads'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiWebhookKiwifyRouteImport } from './routes/api/webhook/kiwify'
import { Route as AuthenticatedMusicasTrackIdRouteImport } from './routes/_authenticated.musicas.$trackId'
import { Route as AuthenticatedLouvorTrackIdRouteImport } from './routes/_authenticated.louvor.$trackId'
import { Route as AuthenticatedCursosCourseIdRouteImport } from './routes/_authenticated.cursos.$courseId'
import { Route as AuthenticatedConteudoTrackIdRouteImport } from './routes/_authenticated.conteudo.$trackId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminTracksRouteImport } from './routes/_authenticated.admin.tracks'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated.admin.integrations'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated.admin.courses'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated.admin.categories'
import { Route as AuthenticatedAdminCoursesNewRouteImport } from './routes/_authenticated.admin.courses.new'
import { Route as AuthenticatedAdminCoursesCourseIdRouteImport } from './routes/_authenticated.admin.courses.$courseId'

const WebhookRoute = WebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMusicasRoute = AuthenticatedMusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiWebhookKiwifyRoute = ApiWebhookKiwifyRouteImport.update({
  id: '/api/webhook/kiwify',
  path: '/api/webhook/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMusicasTrackIdRoute =
  AuthenticatedMusicasTrackIdRouteImport.update({
    id: '/$trackId',
    path: '/$trackId',
    getParentRoute: () => AuthenticatedMusicasRoute,
  } as any)
const AuthenticatedLouvorTrackIdRoute =
  AuthenticatedLouvorTrackIdRouteImport.update({
    id: '/louvor/$trackId',
    path: '/louvor/$trackId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCursosCourseIdRoute =
  AuthenticatedCursosCourseIdRouteImport.update({
    id: '/cursos/$courseId',
    path: '/cursos/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConteudoTrackIdRoute =
  AuthenticatedConteudoTrackIdRouteImport.update({
    id: '/conteudo/$trackId',
    path: '/conteudo/$trackId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTracksRoute =
  AuthenticatedAdminTracksRouteImport.update({
    id: '/tracks',
    path: '/tracks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesNewRoute =
  AuthenticatedAdminCoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdRoute =
  AuthenticatedAdminCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/webhook': typeof WebhookRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/musicas': typeof AuthenticatedMusicasRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/tracks': typeof AuthenticatedAdminTracksRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/conteudo/$trackId': typeof AuthenticatedConteudoTrackIdRoute
  '/cursos/$courseId': typeof AuthenticatedCursosCourseIdRoute
  '/louvor/$trackId': typeof AuthenticatedLouvorTrackIdRoute
  '/musicas/$trackId': typeof AuthenticatedMusicasTrackIdRoute
  '/api/webhook/kiwify': typeof ApiWebhookKiwifyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/webhook': typeof WebhookRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/musicas': typeof AuthenticatedMusicasRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/tracks': typeof AuthenticatedAdminTracksRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/conteudo/$trackId': typeof AuthenticatedConteudoTrackIdRoute
  '/cursos/$courseId': typeof AuthenticatedCursosCourseIdRoute
  '/louvor/$trackId': typeof AuthenticatedLouvorTrackIdRoute
  '/musicas/$trackId': typeof AuthenticatedMusicasTrackIdRoute
  '/api/webhook/kiwify': typeof ApiWebhookKiwifyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/webhook': typeof WebhookRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/musicas': typeof AuthenticatedMusicasRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/tracks': typeof AuthenticatedAdminTracksRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/conteudo/$trackId': typeof AuthenticatedConteudoTrackIdRoute
  '/_authenticated/cursos/$courseId': typeof AuthenticatedCursosCourseIdRoute
  '/_authenticated/louvor/$trackId': typeof AuthenticatedLouvorTrackIdRoute
  '/_authenticated/musicas/$trackId': typeof AuthenticatedMusicasTrackIdRoute
  '/api/webhook/kiwify': typeof ApiWebhookKiwifyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/_authenticated/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/webhook'
    | '/admin'
    | '/downloads'
    | '/musicas'
    | '/perfil'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/integrations'
    | '/admin/tracks'
    | '/admin/users'
    | '/conteudo/$trackId'
    | '/cursos/$courseId'
    | '/louvor/$trackId'
    | '/musicas/$trackId'
    | '/api/webhook/kiwify'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/webhook'
    | '/downloads'
    | '/musicas'
    | '/perfil'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/integrations'
    | '/admin/tracks'
    | '/admin/users'
    | '/conteudo/$trackId'
    | '/cursos/$courseId'
    | '/louvor/$trackId'
    | '/musicas/$trackId'
    | '/api/webhook/kiwify'
    | '/admin'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/webhook'
    | '/_authenticated/admin'
    | '/_authenticated/downloads'
    | '/_authenticated/musicas'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/tracks'
    | '/_authenticated/admin/users'
    | '/_authenticated/conteudo/$trackId'
    | '/_authenticated/cursos/$courseId'
    | '/_authenticated/louvor/$trackId'
    | '/_authenticated/musicas/$trackId'
    | '/api/webhook/kiwify'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/courses/$courseId'
    | '/_authenticated/admin/courses/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  WebhookRoute: typeof WebhookRoute
  ApiWebhookKiwifyRoute: typeof ApiWebhookKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhook': {
      id: '/webhook'
      path: '/webhook'
      fullPath: '/webhook'
      preLoaderRoute: typeof WebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/musicas': {
      id: '/_authenticated/musicas'
      path: '/musicas'
      fullPath: '/musicas'
      preLoaderRoute: typeof AuthenticatedMusicasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/webhook/kiwify': {
      id: '/api/webhook/kiwify'
      path: '/api/webhook/kiwify'
      fullPath: '/api/webhook/kiwify'
      preLoaderRoute: typeof ApiWebhookKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/musicas/$trackId': {
      id: '/_authenticated/musicas/$trackId'
      path: '/$trackId'
      fullPath: '/musicas/$trackId'
      preLoaderRoute: typeof AuthenticatedMusicasTrackIdRouteImport
      parentRoute: typeof AuthenticatedMusicasRoute
    }
    '/_authenticated/louvor/$trackId': {
      id: '/_authenticated/louvor/$trackId'
      path: '/louvor/$trackId'
      fullPath: '/louvor/$trackId'
      preLoaderRoute: typeof AuthenticatedLouvorTrackIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cursos/$courseId': {
      id: '/_authenticated/cursos/$courseId'
      path: '/cursos/$courseId'
      fullPath: '/cursos/$courseId'
      preLoaderRoute: typeof AuthenticatedCursosCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conteudo/$trackId': {
      id: '/_authenticated/conteudo/$trackId'
      path: '/conteudo/$trackId'
      fullPath: '/conteudo/$trackId'
      preLoaderRoute: typeof AuthenticatedConteudoTrackIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tracks': {
      id: '/_authenticated/admin/tracks'
      path: '/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof AuthenticatedAdminTracksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/new': {
      id: '/_authenticated/admin/courses/new'
      path: '/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AuthenticatedAdminCoursesNewRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/admin/courses/$courseId': {
      id: '/_authenticated/admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
  }
}

interface AuthenticatedAdminCoursesRouteChildren {
  AuthenticatedAdminCoursesCourseIdRoute: typeof AuthenticatedAdminCoursesCourseIdRoute
  AuthenticatedAdminCoursesNewRoute: typeof AuthenticatedAdminCoursesNewRoute
}

const AuthenticatedAdminCoursesRouteChildren: AuthenticatedAdminCoursesRouteChildren =
  {
    AuthenticatedAdminCoursesCourseIdRoute:
      AuthenticatedAdminCoursesCourseIdRoute,
    AuthenticatedAdminCoursesNewRoute: AuthenticatedAdminCoursesNewRoute,
  }

const AuthenticatedAdminCoursesRouteWithChildren =
  AuthenticatedAdminCoursesRoute._addFileChildren(
    AuthenticatedAdminCoursesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRouteWithChildren
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminTracksRoute: typeof AuthenticatedAdminTracksRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRouteWithChildren,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminTracksRoute: AuthenticatedAdminTracksRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMusicasRouteChildren {
  AuthenticatedMusicasTrackIdRoute: typeof AuthenticatedMusicasTrackIdRoute
}

const AuthenticatedMusicasRouteChildren: AuthenticatedMusicasRouteChildren = {
  AuthenticatedMusicasTrackIdRoute: AuthenticatedMusicasTrackIdRoute,
}

const AuthenticatedMusicasRouteWithChildren =
  AuthenticatedMusicasRoute._addFileChildren(AuthenticatedMusicasRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedMusicasRoute: typeof AuthenticatedMusicasRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedConteudoTrackIdRoute: typeof AuthenticatedConteudoTrackIdRoute
  AuthenticatedCursosCourseIdRoute: typeof AuthenticatedCursosCourseIdRoute
  AuthenticatedLouvorTrackIdRoute: typeof AuthenticatedLouvorTrackIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedMusicasRoute: AuthenticatedMusicasRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedConteudoTrackIdRoute: AuthenticatedConteudoTrackIdRoute,
  AuthenticatedCursosCourseIdRoute: AuthenticatedCursosCourseIdRoute,
  AuthenticatedLouvorTrackIdRoute: AuthenticatedLouvorTrackIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  WebhookRoute: WebhookRoute,
  ApiWebhookKiwifyRoute: ApiWebhookKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
