/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhookRouteImport } from './routes/webhook'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrilhasRouteImport } from './routes/_authenticated.trilhas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedLancamentosRouteImport } from './routes/_authenticated.lancamentos'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedEbooksRouteImport } from './routes/_authenticated.ebooks'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated.downloads'
import { Route as AuthenticatedCursosRouteImport } from './routes/_authenticated.cursos'
import { Route as AuthenticatedConteudoRouteImport } from './routes/_authenticated.conteudo'
import { Route as AuthenticatedComunidadeRouteImport } from './routes/_authenticated.comunidade'
import { Route as AuthenticatedBonusRouteImport } from './routes/_authenticated.bonus'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedCursosIndexRouteImport } from './routes/_authenticated.cursos.index'
import { Route as AuthenticatedConteudoIndexRouteImport } from './routes/_authenticated.conteudo.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiWebhookKiwifyRouteImport } from './routes/api/webhook/kiwify'
import { Route as AuthenticatedCursosCourseIdRouteImport } from './routes/_authenticated.cursos.$courseId'
import { Route as AuthenticatedConteudoTrackIdRouteImport } from './routes/_authenticated.conteudo.$trackId'
import { Route as AuthenticatedAdminUpsellsRouteImport } from './routes/_authenticated.admin.upsells'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated.admin.courses'
import { Route as AuthenticatedCursosCourseIdIndexRouteImport } from './routes/_authenticated.cursos.$courseId.index'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated.admin.courses.index'
import { Route as AuthenticatedAdminCoursesNewRouteImport } from './routes/_authenticated.admin.courses.new'
import { Route as AuthenticatedAdminCoursesCourseIdRouteImport } from './routes/_authenticated.admin.courses.$courseId'
import { Route as AuthenticatedCursosCourseIdAulaLessonIdRouteImport } from './routes/_authenticated.cursos.$courseId.aula.$lessonId'

const WebhookRoute = WebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrilhasRoute = AuthenticatedTrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLancamentosRoute =
  AuthenticatedLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEbooksRoute = AuthenticatedEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCursosRoute = AuthenticatedCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConteudoRoute = AuthenticatedConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComunidadeRoute = AuthenticatedComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBonusRoute = AuthenticatedBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCursosIndexRoute =
  AuthenticatedCursosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCursosRoute,
  } as any)
const AuthenticatedConteudoIndexRoute =
  AuthenticatedConteudoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConteudoRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiWebhookKiwifyRoute = ApiWebhookKiwifyRouteImport.update({
  id: '/api/webhook/kiwify',
  path: '/api/webhook/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCursosCourseIdRoute =
  AuthenticatedCursosCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedCursosRoute,
  } as any)
const AuthenticatedConteudoTrackIdRoute =
  AuthenticatedConteudoTrackIdRouteImport.update({
    id: '/$trackId',
    path: '/$trackId',
    getParentRoute: () => AuthenticatedConteudoRoute,
  } as any)
const AuthenticatedAdminUpsellsRoute =
  AuthenticatedAdminUpsellsRouteImport.update({
    id: '/upsells',
    path: '/upsells',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCursosCourseIdIndexRoute =
  AuthenticatedCursosCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCursosCourseIdRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminCoursesNewRoute =
  AuthenticatedAdminCoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdRoute =
  AuthenticatedAdminCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedCursosCourseIdAulaLessonIdRoute =
  AuthenticatedCursosCourseIdAulaLessonIdRouteImport.update({
    id: '/aula/$lessonId',
    path: '/aula/$lessonId',
    getParentRoute: () => AuthenticatedCursosCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/webhook': typeof WebhookRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bonus': typeof AuthenticatedBonusRoute
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/conteudo': typeof AuthenticatedConteudoRouteWithChildren
  '/cursos': typeof AuthenticatedCursosRouteWithChildren
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/ebooks': typeof AuthenticatedEbooksRoute
  '/home': typeof AuthenticatedHomeRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/trilhas': typeof AuthenticatedTrilhasRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/upsells': typeof AuthenticatedAdminUpsellsRoute
  '/conteudo/$trackId': typeof AuthenticatedConteudoTrackIdRoute
  '/cursos/$courseId': typeof AuthenticatedCursosCourseIdRouteWithChildren
  '/api/webhook/kiwify': typeof ApiWebhookKiwifyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/conteudo/': typeof AuthenticatedConteudoIndexRoute
  '/cursos/': typeof AuthenticatedCursosIndexRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/cursos/$courseId/': typeof AuthenticatedCursosCourseIdIndexRoute
  '/cursos/$courseId/aula/$lessonId': typeof AuthenticatedCursosCourseIdAulaLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/webhook': typeof WebhookRoute
  '/bonus': typeof AuthenticatedBonusRoute
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/ebooks': typeof AuthenticatedEbooksRoute
  '/home': typeof AuthenticatedHomeRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/trilhas': typeof AuthenticatedTrilhasRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/upsells': typeof AuthenticatedAdminUpsellsRoute
  '/conteudo/$trackId': typeof AuthenticatedConteudoTrackIdRoute
  '/api/webhook/kiwify': typeof ApiWebhookKiwifyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/conteudo': typeof AuthenticatedConteudoIndexRoute
  '/cursos': typeof AuthenticatedCursosIndexRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/cursos/$courseId': typeof AuthenticatedCursosCourseIdIndexRoute
  '/cursos/$courseId/aula/$lessonId': typeof AuthenticatedCursosCourseIdAulaLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/webhook': typeof WebhookRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/bonus': typeof AuthenticatedBonusRoute
  '/_authenticated/comunidade': typeof AuthenticatedComunidadeRoute
  '/_authenticated/conteudo': typeof AuthenticatedConteudoRouteWithChildren
  '/_authenticated/cursos': typeof AuthenticatedCursosRouteWithChildren
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/ebooks': typeof AuthenticatedEbooksRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/lancamentos': typeof AuthenticatedLancamentosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/trilhas': typeof AuthenticatedTrilhasRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/upsells': typeof AuthenticatedAdminUpsellsRoute
  '/_authenticated/conteudo/$trackId': typeof AuthenticatedConteudoTrackIdRoute
  '/_authenticated/cursos/$courseId': typeof AuthenticatedCursosCourseIdRouteWithChildren
  '/api/webhook/kiwify': typeof ApiWebhookKiwifyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/conteudo/': typeof AuthenticatedConteudoIndexRoute
  '/_authenticated/cursos/': typeof AuthenticatedCursosIndexRoute
  '/_authenticated/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/_authenticated/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/cursos/$courseId/': typeof AuthenticatedCursosCourseIdIndexRoute
  '/_authenticated/cursos/$courseId/aula/$lessonId': typeof AuthenticatedCursosCourseIdAulaLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/webhook'
    | '/admin'
    | '/bonus'
    | '/comunidade'
    | '/conteudo'
    | '/cursos'
    | '/downloads'
    | '/ebooks'
    | '/home'
    | '/lancamentos'
    | '/perfil'
    | '/trilhas'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/upsells'
    | '/conteudo/$trackId'
    | '/cursos/$courseId'
    | '/api/webhook/kiwify'
    | '/admin/'
    | '/conteudo/'
    | '/cursos/'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/courses/'
    | '/cursos/$courseId/'
    | '/cursos/$courseId/aula/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/webhook'
    | '/bonus'
    | '/comunidade'
    | '/downloads'
    | '/ebooks'
    | '/home'
    | '/lancamentos'
    | '/perfil'
    | '/trilhas'
    | '/admin/dashboard'
    | '/admin/upsells'
    | '/conteudo/$trackId'
    | '/api/webhook/kiwify'
    | '/admin'
    | '/conteudo'
    | '/cursos'
    | '/admin/courses/$courseId'
    | '/admin/courses/new'
    | '/admin/courses'
    | '/cursos/$courseId'
    | '/cursos/$courseId/aula/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/webhook'
    | '/_authenticated/admin'
    | '/_authenticated/bonus'
    | '/_authenticated/comunidade'
    | '/_authenticated/conteudo'
    | '/_authenticated/cursos'
    | '/_authenticated/downloads'
    | '/_authenticated/ebooks'
    | '/_authenticated/home'
    | '/_authenticated/lancamentos'
    | '/_authenticated/perfil'
    | '/_authenticated/trilhas'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/upsells'
    | '/_authenticated/conteudo/$trackId'
    | '/_authenticated/cursos/$courseId'
    | '/api/webhook/kiwify'
    | '/_authenticated/admin/'
    | '/_authenticated/conteudo/'
    | '/_authenticated/cursos/'
    | '/_authenticated/admin/courses/$courseId'
    | '/_authenticated/admin/courses/new'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/cursos/$courseId/'
    | '/_authenticated/cursos/$courseId/aula/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  WebhookRoute: typeof WebhookRoute
  ApiWebhookKiwifyRoute: typeof ApiWebhookKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhook': {
      id: '/webhook'
      path: '/webhook'
      fullPath: '/webhook'
      preLoaderRoute: typeof WebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trilhas': {
      id: '/_authenticated/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof AuthenticatedTrilhasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lancamentos': {
      id: '/_authenticated/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AuthenticatedLancamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ebooks': {
      id: '/_authenticated/ebooks'
      path: '/ebooks'
      fullPath: '/ebooks'
      preLoaderRoute: typeof AuthenticatedEbooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cursos': {
      id: '/_authenticated/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof AuthenticatedCursosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conteudo': {
      id: '/_authenticated/conteudo'
      path: '/conteudo'
      fullPath: '/conteudo'
      preLoaderRoute: typeof AuthenticatedConteudoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunidade': {
      id: '/_authenticated/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof AuthenticatedComunidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bonus': {
      id: '/_authenticated/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof AuthenticatedBonusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cursos/': {
      id: '/_authenticated/cursos/'
      path: '/'
      fullPath: '/cursos/'
      preLoaderRoute: typeof AuthenticatedCursosIndexRouteImport
      parentRoute: typeof AuthenticatedCursosRoute
    }
    '/_authenticated/conteudo/': {
      id: '/_authenticated/conteudo/'
      path: '/'
      fullPath: '/conteudo/'
      preLoaderRoute: typeof AuthenticatedConteudoIndexRouteImport
      parentRoute: typeof AuthenticatedConteudoRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/webhook/kiwify': {
      id: '/api/webhook/kiwify'
      path: '/api/webhook/kiwify'
      fullPath: '/api/webhook/kiwify'
      preLoaderRoute: typeof ApiWebhookKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cursos/$courseId': {
      id: '/_authenticated/cursos/$courseId'
      path: '/$courseId'
      fullPath: '/cursos/$courseId'
      preLoaderRoute: typeof AuthenticatedCursosCourseIdRouteImport
      parentRoute: typeof AuthenticatedCursosRoute
    }
    '/_authenticated/conteudo/$trackId': {
      id: '/_authenticated/conteudo/$trackId'
      path: '/$trackId'
      fullPath: '/conteudo/$trackId'
      preLoaderRoute: typeof AuthenticatedConteudoTrackIdRouteImport
      parentRoute: typeof AuthenticatedConteudoRoute
    }
    '/_authenticated/admin/upsells': {
      id: '/_authenticated/admin/upsells'
      path: '/upsells'
      fullPath: '/admin/upsells'
      preLoaderRoute: typeof AuthenticatedAdminUpsellsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/cursos/$courseId/': {
      id: '/_authenticated/cursos/$courseId/'
      path: '/'
      fullPath: '/cursos/$courseId/'
      preLoaderRoute: typeof AuthenticatedCursosCourseIdIndexRouteImport
      parentRoute: typeof AuthenticatedCursosCourseIdRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/admin/courses/new': {
      id: '/_authenticated/admin/courses/new'
      path: '/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AuthenticatedAdminCoursesNewRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/admin/courses/$courseId': {
      id: '/_authenticated/admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/cursos/$courseId/aula/$lessonId': {
      id: '/_authenticated/cursos/$courseId/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/cursos/$courseId/aula/$lessonId'
      preLoaderRoute: typeof AuthenticatedCursosCourseIdAulaLessonIdRouteImport
      parentRoute: typeof AuthenticatedCursosCourseIdRoute
    }
  }
}

interface AuthenticatedAdminCoursesRouteChildren {
  AuthenticatedAdminCoursesCourseIdRoute: typeof AuthenticatedAdminCoursesCourseIdRoute
  AuthenticatedAdminCoursesNewRoute: typeof AuthenticatedAdminCoursesNewRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
}

const AuthenticatedAdminCoursesRouteChildren: AuthenticatedAdminCoursesRouteChildren =
  {
    AuthenticatedAdminCoursesCourseIdRoute:
      AuthenticatedAdminCoursesCourseIdRoute,
    AuthenticatedAdminCoursesNewRoute: AuthenticatedAdminCoursesNewRoute,
    AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
  }

const AuthenticatedAdminCoursesRouteWithChildren =
  AuthenticatedAdminCoursesRoute._addFileChildren(
    AuthenticatedAdminCoursesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminUpsellsRoute: typeof AuthenticatedAdminUpsellsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminUpsellsRoute: AuthenticatedAdminUpsellsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedConteudoRouteChildren {
  AuthenticatedConteudoTrackIdRoute: typeof AuthenticatedConteudoTrackIdRoute
  AuthenticatedConteudoIndexRoute: typeof AuthenticatedConteudoIndexRoute
}

const AuthenticatedConteudoRouteChildren: AuthenticatedConteudoRouteChildren = {
  AuthenticatedConteudoTrackIdRoute: AuthenticatedConteudoTrackIdRoute,
  AuthenticatedConteudoIndexRoute: AuthenticatedConteudoIndexRoute,
}

const AuthenticatedConteudoRouteWithChildren =
  AuthenticatedConteudoRoute._addFileChildren(
    AuthenticatedConteudoRouteChildren,
  )

interface AuthenticatedCursosCourseIdRouteChildren {
  AuthenticatedCursosCourseIdIndexRoute: typeof AuthenticatedCursosCourseIdIndexRoute
  AuthenticatedCursosCourseIdAulaLessonIdRoute: typeof AuthenticatedCursosCourseIdAulaLessonIdRoute
}

const AuthenticatedCursosCourseIdRouteChildren: AuthenticatedCursosCourseIdRouteChildren =
  {
    AuthenticatedCursosCourseIdIndexRoute:
      AuthenticatedCursosCourseIdIndexRoute,
    AuthenticatedCursosCourseIdAulaLessonIdRoute:
      AuthenticatedCursosCourseIdAulaLessonIdRoute,
  }

const AuthenticatedCursosCourseIdRouteWithChildren =
  AuthenticatedCursosCourseIdRoute._addFileChildren(
    AuthenticatedCursosCourseIdRouteChildren,
  )

interface AuthenticatedCursosRouteChildren {
  AuthenticatedCursosCourseIdRoute: typeof AuthenticatedCursosCourseIdRouteWithChildren
  AuthenticatedCursosIndexRoute: typeof AuthenticatedCursosIndexRoute
}

const AuthenticatedCursosRouteChildren: AuthenticatedCursosRouteChildren = {
  AuthenticatedCursosCourseIdRoute:
    AuthenticatedCursosCourseIdRouteWithChildren,
  AuthenticatedCursosIndexRoute: AuthenticatedCursosIndexRoute,
}

const AuthenticatedCursosRouteWithChildren =
  AuthenticatedCursosRoute._addFileChildren(AuthenticatedCursosRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBonusRoute: typeof AuthenticatedBonusRoute
  AuthenticatedComunidadeRoute: typeof AuthenticatedComunidadeRoute
  AuthenticatedConteudoRoute: typeof AuthenticatedConteudoRouteWithChildren
  AuthenticatedCursosRoute: typeof AuthenticatedCursosRouteWithChildren
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedEbooksRoute: typeof AuthenticatedEbooksRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLancamentosRoute: typeof AuthenticatedLancamentosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTrilhasRoute: typeof AuthenticatedTrilhasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBonusRoute: AuthenticatedBonusRoute,
  AuthenticatedComunidadeRoute: AuthenticatedComunidadeRoute,
  AuthenticatedConteudoRoute: AuthenticatedConteudoRouteWithChildren,
  AuthenticatedCursosRoute: AuthenticatedCursosRouteWithChildren,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedEbooksRoute: AuthenticatedEbooksRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLancamentosRoute: AuthenticatedLancamentosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTrilhasRoute: AuthenticatedTrilhasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  WebhookRoute: WebhookRoute,
  ApiWebhookKiwifyRoute: ApiWebhookKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
