ALTER TABLE public.areas_membros 
ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#D4AF37',
ADD COLUMN IF NOT EXISTS secondary_color TEXT DEFAULT '#000000',
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS favicon_url TEXT,
ADD COLUMN IF NOT EXISTS banner_url TEXT;