ALTER TABLE public.areas 
ADD COLUMN IF NOT EXISTS favicon_url TEXT,
ADD COLUMN IF NOT EXISTS banner_url TEXT,
ADD COLUMN IF NOT EXISTS secondary_color TEXT DEFAULT '#000000',
ADD COLUMN IF NOT EXISTS background_color TEXT DEFAULT '#000000',
ADD COLUMN IF NOT EXISTS surface_color TEXT DEFAULT '#0A0A0A',
ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'pt-BR',
ADD COLUMN IF NOT EXISTS login_title TEXT,
ADD COLUMN IF NOT EXISTS login_subtitle TEXT,
ADD COLUMN IF NOT EXISTS login_background_url TEXT,
ADD COLUMN IF NOT EXISTS settings JSONB DEFAULT '{}'::jsonb;