ALTER TABLE public.areas_membros 
ADD COLUMN IF NOT EXISTS idiomas_ativos TEXT[] DEFAULT ARRAY['pt-BR'],
ADD COLUMN IF NOT EXISTS formato_data TEXT DEFAULT 'DD/MM/AAAA',
ADD COLUMN IF NOT EXISTS boas_vindas TEXT,
ADD COLUMN IF NOT EXISTS botao_continuar TEXT,
ADD COLUMN IF NOT EXISTS produto_bloqueado TEXT,
ADD COLUMN IF NOT EXISTS conclusao TEXT,
ADD COLUMN IF NOT EXISTS parabens TEXT,
ADD COLUMN IF NOT EXISTS botao_entrar TEXT,
ADD COLUMN IF NOT EXISTS suporte_texto TEXT;
